In [80]:
pip install tensorflow

Note: you may need to restart the kernel to use updated packages.


In [81]:
import tensorflow as tf

In [82]:
tf.__version__

'2.8.0'

In [83]:
########## Resizing all the image to this
Image_Size = [224,224]
training_path = 'C:\\Users\\DELL\\OneDrive - D Cube Analytics Pvt. Ltd\\Desktop\\ML\\Machine Learning A-Z (Codes and Datasets)\\DL-PROJECT\\Dataset\\Train'
test_path = 'C:\\Users\\DELL\\OneDrive - D Cube Analytics Pvt. Ltd\\Desktop\\ML\\Machine Learning A-Z (Codes and Datasets)\\DL-PROJECT\\Dataset\\Test'

In [84]:
################## Importing the Vgg 19 library and applying 

from tensorflow.keras.applications.vgg19 import VGG19

vgg19 = VGG19(input_shape = Image_Size + [3], weights = 'imagenet',  include_top = False)

In [85]:
############# Not training the existing weights 

for layer in vgg19.layers:
    layer.trainable = False

In [86]:
################ useful for checking total number of output classes
from glob import glob
folders = glob('C:\\Users\\DELL\\OneDrive - D Cube Analytics Pvt. Ltd\\Desktop\\ML\\Machine Learning A-Z (Codes and Datasets)\\DL-PROJECT\\Dataset\\Train\\*')
folders

['C:\\Users\\DELL\\OneDrive - D Cube Analytics Pvt. Ltd\\Desktop\\ML\\Machine Learning A-Z (Codes and Datasets)\\DL-PROJECT\\Dataset\\Train\\Parasite',
 'C:\\Users\\DELL\\OneDrive - D Cube Analytics Pvt. Ltd\\Desktop\\ML\\Machine Learning A-Z (Codes and Datasets)\\DL-PROJECT\\Dataset\\Train\\Uninfected']

In [87]:
len(folders)

2

In [88]:
#################### Flattening the output of vgg19

from tensorflow.keras.layers import Flatten
x = Flatten()(vgg19.output)

In [89]:
############### After Flattening adding Dense layer 

from tensorflow.keras.layers import Dense
prediction = Dense(units = len(folders), activation = 'softmax')(x)

In [90]:
############### creating a model object

from tensorflow.keras.models import Model
model = Model(inputs = vgg19.input , outputs = prediction)

In [91]:
################## Viewing the structure of model
model.summary()

Model: "model_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_4 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0   

# Training the model

In [92]:
######### Compiling the model

model.compile(loss = 'categorical_crossentropy', optimizer = 'adam',metrics = ['accuracy'])

In [93]:
################# Using Image Data Generator to import image from dataset

from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255 ,
                                  shear_range = 0.2 ,
                                  zoom_range = 0.2 , 
                                  horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)

In [94]:
training_set = train_datagen.flow_from_directory("C:\\Users\\DELL\\OneDrive - D Cube Analytics Pvt. Ltd\\Desktop\\ML\Machine Learning A-Z (Codes and Datasets)\\DL-PROJECT\\Dataset\\Train",
                                        batch_size = 32,
                                        target_size = (224,224),
                                        class_mode = 'categorical')

training_set

Found 416 images belonging to 2 classes.


In [95]:
test_set = test_datagen.flow_from_directory("C:\\Users\\DELL\\OneDrive - D Cube Analytics Pvt. Ltd\\Desktop\\ML\Machine Learning A-Z (Codes and Datasets)\\DL-PROJECT\\Dataset\\Test",
                                           target_size = (224,224),
                                           batch_size = 32,
                                           class_mode = 'categorical')
test_set

Found 134 images belonging to 2 classes.


In [96]:
len(training_set)

13

In [97]:
len(test_set)

5

In [98]:
#################### Training the model on training set and evaluating on test set

model.fit(training_set , 
          validation_data = test_set , 
          epochs = 2 , 
          steps_per_epoch= len(training_set), 
          validation_steps= len(test_set) )

Epoch 1/2
13/13 [==============================] - 158s 12s/step - loss: 1.6599 - accuracy: 0.5312 - val_loss: 1.8949 - val_accuracy: 0.3358
Epoch 2/2
13/13 [==============================] - 157s 12s/step - loss: 0.7409 - accuracy: 0.6611 - val_loss: 0.5489 - val_accuracy: 0.7239


In [99]:
################### Prediction
y_pred = model.predict(test_set)
y_pred

array([[0.8478895 , 0.15211059],
       [0.54469925, 0.45530072],
       [0.7718878 , 0.22811215],
       [0.7279365 , 0.27206346],
       [0.36801156, 0.6319884 ],
       [0.4335683 , 0.5664317 ],
       [0.9859226 , 0.01407738],
       [0.9146033 , 0.08539674],
       [0.9831141 , 0.01688593],
       [0.784242  , 0.21575806],
       [0.61579514, 0.38420486],
       [0.73015326, 0.2698467 ],
       [0.9975425 , 0.00245755],
       [0.81377757, 0.18622248],
       [0.79946935, 0.20053063],
       [0.82337517, 0.17662482],
       [0.74302894, 0.25697103],
       [0.966814  , 0.03318597],
       [0.938613  , 0.06138694],
       [0.585776  , 0.414224  ],
       [0.6534124 , 0.3465876 ],
       [0.9272706 , 0.07272945],
       [0.8480501 , 0.15194993],
       [0.8992722 , 0.10072777],
       [0.7858898 , 0.21411023],
       [0.8474802 , 0.1525198 ],
       [0.7154462 , 0.28455386],
       [0.93079776, 0.06920225],
       [0.80189866, 0.19810133],
       [0.61481273, 0.38518733],
       [0.

In [100]:
######### Getting the index of maximum element in the y_pred

import numpy as np
y_pred = np.argmax(y_pred , axis = 1)
y_pred

array([0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1], dtype=int64)

y_pred = 0 means person is infected and vice versa

# Making a single prediction

In [101]:
from tensorflow.keras.preprocessing import image

test_image = image.load_img("C:\\Users\\DELL\\OneDrive - D Cube Analytics Pvt. Ltd\\Desktop\\ML\\Machine Learning A-Z (Codes and Datasets)\\DL-PROJECT\\Dataset\\Test\\Parasite\\C39P4thinF_original_IMG_20150622_105803_cell_90.png", target_size = (224,224))
test_image = image.img_to_array(test_image)
test_image

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [102]:
test_image.shape

(224, 224, 3)

In [103]:
test_image = test_image/255

In [104]:
test_image = np.expand_dims(test_image, axis = 0)

In [105]:
################# Predicting the image
model.predict(test_image)

array([[0.93079776, 0.06920221]], dtype=float32)

In [106]:
a = np.argmax(model.predict(test_image), axis = 1)
if (a==1):
    print('Uninfected')
else :
    print('Infected')

Infected
